### ISSUE TITLE
Hardcoded localization spotted

### ISSUE THREAD

**Issue by labpaw** [squeek502/TiC-Tooltips#18]
StringHelper.java lines 33, 35, 53 :smile:  and this http://i.imgur.com/1zVrwxS.jpg
Also, why not to use vanilla Tinkers Construct names? For StringHelper.java stuff.
Some more stuff:
1) Weight string should have %s tag. Additionally it should have "Arrow" string because I need to modify word "Arrow" and swap it with word "Weight".
2) Hardcoded "Bow" string should have %s tag too.
3) tictooltips.tool.effective.durability=Effective %s should have independent "Durability" string because I need write "Durability" lowercase.

**Comment by labpaw** [comment]
You seems to not noticed "Some more stuff:" :smile:

**Comment by squeek502** [comment]
Whoops, didn't see the edit before I committed.

1) Not sure how I should fix this one yet. Note, though, that the arrow string comes from `item.InfiTool.Arrow.name`.
2) I simply removed the "Bow" part of those strings. They weren't really necessary and they would be somewhat of a pain to make them work right with localization.
3) You can just replace that whole string with your own; it doesn't have to have a `%s` in it. For example, `tictooltips.tool.effective.durability=Effective durability:` would work.

**Comment by labpaw** [comment]
Ok. So, point 1 still a problem. Maybe it possible to add this string into TiC Tooltips?
